import bcrypt from 'bcryptjs';
import { ROLES, STATUS, TICKET_STATUS } from '../constants/roles.js';

/**
 * Deterministic seed dataset. Default password for every demo account is
 * "Password123!". These records mirror the normalised PostgreSQL schema.
 */
const pw = bcrypt.hashSync('Password123!', 10);
const iso = (daysAgo = 0) =>
  new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000).toISOString();

const users = [
  {
    id: 'usr_superadmin',
    name: 'Ava Okafor',
    email: 'super@avaanaspace.com',
    passwordHash: pw,
    role: ROLES.SUPER_ADMIN,
    status: STATUS.APPROVED,
    avatarUrl: '',
    bio: 'Founder & platform steward.',
    createdAt: iso(120),
    deletedAt: null,
  },
  {
    id: 'usr_admin',
    name: 'Marcus Bell',
    email: 'admin@avaanaspace.com',
    passwordHash: pw,
    role: ROLES.ADMIN,
    status: STATUS.APPROVED,
    avatarUrl: '',
    bio: 'Trust & safety lead.',
    createdAt: iso(90),
    deletedAt: null,
  },
  {
    id: 'usr_owner1',
    name: 'Priya Nair',
    email: 'priya@brightbrew.com',
    passwordHash: pw,
    role: ROLES.BUSINESS_OWNER,
    status: STATUS.APPROVED,
    avatarUrl: '',
    bio: 'Roaster & owner at BrightBrew.',
    createdAt: iso(60),
    deletedAt: null,
  },
  {
    id: 'usr_owner2',
    name: 'Diego Santos',
    email: 'diego@pixelforge.io',
    passwordHash: pw,
    role: ROLES.BUSINESS_OWNER,
    status: STATUS.APPROVED,
    avatarUrl: '',
    bio: 'Design studio founder.',
    createdAt: iso(45),
    deletedAt: null,
  },
  {
    id: 'usr_member',
    name: 'Lena Kim',
    email: 'lena@example.com',
    passwordHash: pw,
    role: ROLES.USER,
    status: STATUS.APPROVED,
    avatarUrl: '',
    bio: 'Curious explorer.',
    createdAt: iso(30),
    deletedAt: null,
  },
];

const businesses = [
  {
    id: 'biz_brightbrew',
    ownerId: 'usr_owner1',
    name: 'BrightBrew Coffee',
    slug: 'brightbrew-coffee',
    category: 'Food & Beverage',
    tagline: 'Small-batch specialty coffee, roasted with care.',
    description:
      'BrightBrew is a specialty micro-roaster sourcing ethical beans from single-origin farms. We craft vibrant, traceable coffee for cafés and homes.',
    logoUrl: '',
    coverUrl: '',
    gallery: [],
    website: 'https://brightbrew.example.com',
    location: 'Portland, OR',
    verified: true,
    status: STATUS.APPROVED,
    followers: 1284,
    rating: 4.8,
    createdAt: iso(58),
    deletedAt: null,
  },
  {
    id: 'biz_pixelforge',
    ownerId: 'usr_owner2',
    name: 'PixelForge Studio',
    slug: 'pixelforge-studio',
    category: 'Design & Creative',
    tagline: 'Product design for ambitious teams.',
    description:
      'PixelForge is a boutique design studio partnering with startups to ship beautiful, accessible products end to end.',
    logoUrl: '',
    coverUrl: '',
    gallery: [],
    website: 'https://pixelforge.example.com',
    location: 'Lisbon, PT',
    verified: true,
    status: STATUS.APPROVED,
    followers: 872,
    rating: 4.9,
    createdAt: iso(44),
    deletedAt: null,
  },
  {
    id: 'biz_pending',
    ownerId: 'usr_owner2',
    name: 'GreenLeaf Botanicals',
    slug: 'greenleaf-botanicals',
    category: 'Health & Wellness',
    tagline: 'Plant-forward wellness essentials.',
    description: 'Sustainably sourced botanicals and wellness kits.',
    logoUrl: '',
    coverUrl: '',
    gallery: [],
    website: '',
    location: 'Austin, TX',
    verified: false,
    status: STATUS.PENDING,
    followers: 0,
    rating: 0,
    createdAt: iso(2),
    deletedAt: null,
  },
];

const products = [
  {
    id: 'prd_ethiopia',
    businessId: 'biz_brightbrew',
    name: 'Ethiopia Yirgacheffe',
    slug: 'ethiopia-yirgacheffe',
    price: 19.5,
    currency: 'USD',
    category: 'Coffee',
    description: 'Floral, citrus-forward washed coffee. 340g whole bean.',
    imageUrl: '',
    stock: 120,
    status: STATUS.APPROVED,
    rating: 4.9,
    sales: 340,
    createdAt: iso(40),
    deletedAt: null,
  },
  {
    id: 'prd_colombia',
    businessId: 'biz_brightbrew',
    name: 'Colombia Huila',
    slug: 'colombia-huila',
    price: 17.0,
    currency: 'USD',
    category: 'Coffee',
    description: 'Balanced, caramel sweetness with a smooth finish. 340g.',
    imageUrl: '',
    stock: 80,
    status: STATUS.APPROVED,
    rating: 4.7,
    sales: 210,
    createdAt: iso(35),
    deletedAt: null,
  },
  {
    id: 'prd_designsprint',
    businessId: 'biz_pixelforge',
    name: 'Design Sprint Package',
    slug: 'design-sprint-package',
    price: 4500,
    currency: 'USD',
    category: 'Services',
    description: 'A focused 5-day sprint from problem to validated prototype.',
    imageUrl: '',
    stock: 5,
    status: STATUS.APPROVED,
    rating: 5.0,
    sales: 12,
    createdAt: iso(30),
    deletedAt: null,
  },
  {
    id: 'prd_pending',
    businessId: 'biz_brightbrew',
    name: 'Cold Brew Concentrate',
    slug: 'cold-brew-concentrate',
    price: 24.0,
    currency: 'USD',
    category: 'Coffee',
    description: 'Slow-steeped concentrate, makes 12 servings.',
    imageUrl: '',
    stock: 40,
    status: STATUS.PENDING,
    rating: 0,
    sales: 0,
    createdAt: iso(1),
    deletedAt: null,
  },
];

const spaces = [
  {
    id: 'spc_founders',
    name: 'Founders Circle',
    slug: 'founders-circle',
    description: 'A community for early-stage founders to share and learn.',
    visibility: 'public',
    official: true,
    ownerId: 'usr_admin',
    members: 3421,
    createdAt: iso(50),
    deletedAt: null,
  },
  {
    id: 'spc_makers',
    name: 'Makers & Roasters',
    slug: 'makers-roasters',
    description: 'For specialty food & beverage makers.',
    visibility: 'public',
    official: false,
    ownerId: 'usr_owner1',
    members: 918,
    createdAt: iso(40),
    deletedAt: null,
  },
  {
    id: 'spc_design',
    name: 'Product Design Guild',
    slug: 'product-design-guild',
    description: 'Craft, critique and career for product designers.',
    visibility: 'private',
    official: false,
    ownerId: 'usr_owner2',
    members: 640,
    createdAt: iso(30),
    deletedAt: null,
  },
];

const posts = [
  {
    id: 'pst_1',
    spaceId: 'spc_founders',
    authorId: 'usr_owner1',
    title: 'How we hit our first 1,000 customers',
    body: 'Sharing the exact playbook we used for organic growth in year one.',
    likes: 128,
    commentsCount: 24,
    createdAt: iso(5),
    deletedAt: null,
  },
  {
    id: 'pst_2',
    spaceId: 'spc_design',
    authorId: 'usr_owner2',
    title: 'Accessible color systems that scale',
    body: 'A practical guide to building WCAG AA compliant palettes.',
    likes: 96,
    commentsCount: 15,
    createdAt: iso(3),
    deletedAt: null,
  },
];

const tickets = [
  {
    id: 'tkt_1001',
    reference: 'AVN-1001',
    customerId: 'usr_member',
    businessId: 'biz_brightbrew',
    productId: 'prd_ethiopia',
    subject: 'Question about subscription options',
    status: TICKET_STATUS.FORWARDED_TO_BUSINESS,
    priority: 'normal',
    createdAt: iso(2),
    deletedAt: null,
  },
];

const ticketMessages = [
  {
    id: 'tmsg_1',
    ticketId: 'tkt_1001',
    senderId: 'usr_member',
    senderRole: ROLES.USER,
    audience: 'admin',
    body: 'Do you offer a monthly subscription for the Yirgacheffe beans?',
    createdAt: iso(2),
    deletedAt: null,
  },
  {
    id: 'tmsg_2',
    ticketId: 'tkt_1001',
    senderId: 'usr_admin',
    senderRole: ROLES.ADMIN,
    audience: 'business',
    body: 'Forwarding this customer enquiry — please advise on subscription availability.',
    createdAt: iso(1),
    deletedAt: null,
  },
];

const notifications = [
  {
    id: 'ntf_1',
    userId: 'usr_owner1',
    category: 'marketplace',
    title: 'New customer enquiry',
    body: 'A customer asked about Ethiopia Yirgacheffe.',
    read: false,
    createdAt: iso(1),
    deletedAt: null,
  },
  {
    id: 'ntf_2',
    userId: 'usr_owner1',
    category: 'business',
    title: 'Your business is verified',
    body: 'BrightBrew Coffee earned a verification badge.',
    read: true,
    createdAt: iso(10),
    deletedAt: null,
  },
  {
    id: 'ntf_3',
    userId: 'usr_admin',
    category: 'moderation',
    title: 'New product awaiting approval',
    body: 'Cold Brew Concentrate is pending review.',
    read: false,
    createdAt: iso(1),
    deletedAt: null,
  },
];

export const seedData = {
  users,
  businesses,
  products,
  spaces,
  posts,
  tickets,
  ticketMessages,
  notifications,
};
